package com.kraken.plugin.functions

import com.google.gson.Gson
import com.google.gson.annotations.SerializedName

/**
 * Fixed catalogue of KEL native functions.
 *
 * The engine discovers functions at runtime (`ServiceLoader` on `FunctionLibrary`, see
 * `kraken.el.functionregistry.FunctionRegistry`). RuleScribe runs nothing and does not
 * depend on the engine, so it bundles a copy of the catalogue generated from the engine
 * sources by `tools/gen_functions.py`. Never edit it by hand.
 *
 * The engine identifies a function by name and parameter count, not by types, so
 * [find] returns at most one result.
 */
object KrakenFunctionCatalog {

    /** All native functions, sorted by name then arity. */
    val functions: List<KelFunction> by lazy { load().functions }

    val libraries: List<KelLibrary> by lazy { load().libraries }

    private val byName: Map<String, List<KelFunction>> by lazy {
        functions.groupBy { it.name }
    }

    /** Overloads with this name, of any arity. */
    fun byName(name: String): List<KelFunction> = byName[name].orEmpty()

    /** The function matching the engine identity (name, arity) exactly. */
    fun find(name: String, arity: Int): KelFunction? = byName(name).firstOrNull { it.parameters.size == arity }

    private fun load(): Catalog = KrakenFunctionCatalog::class.java.getResourceAsStream(RESOURCE)
        ?.reader(Charsets.UTF_8)
        ?.use { Gson().fromJson(it, Catalog::class.java) }
        ?: Catalog(emptyList(), emptyList())

    private const val RESOURCE = "/functions/kel-functions.json"

    private class Catalog(val libraries: List<KelLibrary>, val functions: List<KelFunction>)
}

/**
 * An engine library (Math, String, Date…).
 *
 * Only the count is read, by the test pinning 55 native functions in 9 libraries, which
 * guards the catalogue generated by `tools/gen_functions.py`. The fields mirror the
 * JSON; Gson fills them and nothing reads them, hence `@Suppress`.
 */
@Suppress("unused")
class KelLibrary(
    val name: String,
    val description: String?,
    val since: String?,
)

class KelFunction(
    val name: String,
    val library: String,
    val parameters: List<KelParameter>,
    @SerializedName("returnType") val returnType: String,
    val description: String?,
    val since: String?,
    val examples: List<KelExample>,
) {
    /** `Round(Number number, Number scale) : Number` */
    fun signature(): String = "$name(${parameters.joinToString(", ") { it.presentation() }}) : $returnType"
}

class KelParameter(
    val name: String,
    val type: String,
    val required: Boolean,
) {
    fun presentation(): String = "$type $name"
}

class KelExample(
    val expression: String,
    val result: String?,
)
